### ISSUE TITLE
Stuck on caddy v1 because i use http filters in v1 ...

### ISSUE THREAD

**Issue by BobCashStory** [caddyserver/response-replace#1]
Hello you to let you know you removed the doc of v1 in the website it make it difficult to me to use caddy but i can't migrate i really need this, i think to find a way to go back on nginx because of that, do you have any roadmap for that feature ?

i would like to help, but the only time i try golang i disliked so much that was crazy, i can probaly paid for that one that a current too big pain 😢 
my current use :

```
          naas.ai {
              import basicSnip
              proxy / hub:8000 {
                  transparent
                  websocket
              }
              filter rule {
                  content_type text/html.*
                  search_pattern "</head>"
                  replacement "<script src=\"https://cdn.jsdelivr.net/npm/bob_rpa@1.3.5/jupyter.js\"></script></head>"
              }
          }
```
I add code to have custom css in platform and custom js, like autofill password in iframed.

**Comment by mholt** [comment]
> you removed the doc of v1 in the website

Caddy v1 docs are linked right in the main navigation of the docs:

![Screenshot from 2020-10-05 10-05-00](https://user-images.githubusercontent.com/1128849/95103791-4e461480-06f2-11eb-940b-86f2ea744906.png)

Anyway, this feature is actually already implemented. I'm waiting for a client to get back to us before I publish it.

**Comment by BobCashStory** [comment]
Thanks a lot ! <3

**Comment by BobCashStory** [comment]
@mholt do you know in what timeline that can go out ?

**Comment by mholt** [comment]
@BobCashStory Mmm, well, I haven't heard from the client yet, and actually there isn't a contract or anything at this point, so I guess I can just publish it and have people start testing/using it. Give me a few hours to finish up something and I'll push it.

**Comment by mholt** [comment]
lol I'm gonna rename this to `replace-response` since `response-replace` doesn't make much sense... push incoming!

**Comment by mholt** [comment]
@BobCashStory Okay, it's published! Still a very early version but was working for me.

**Comment by BobCashStory** [comment]
@mholt i will check tomorrow thanks a lot !
